GET http://localhost:8000/api/hexalenergy/designs

####################################################################################

GET http://localhost:8000/api/orders/66

####################################################################################

POST http://localhost:8000/api/place-order/ http/1.1
Content-Type: application/json

{
    "products": [
        {
            "product_id" : 66,
            "qty" : 1 
        }
    ],
    "address": {
        "address_line1" : "Flat no:401",
        "address_line2" : "Satya Castle,Shanti Nagar",
        "state" : "Andhra Pradesh",
        "city" : "Visakhapatnam",
        "country" : "India",
        "pincode" : "530009",
        "telephone":"8074298749",
        "account":"2"
    },
    "success_url": "http://localhost:8000/",
    "cancelled_url": "http://localhost:8000/"
}
